name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: 8.2
        php_extensions: gd zip intl
        dev: yes
    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      with:
        php_version: 8.2
        configuration: "Tests/phpunit.xml"
        memory_limt: "32M"
        php_extensions: intl